[package]
name = "discord-message-parser"
version = "0.1.0"
edition = "2018"

[features]
serenity = ["dep_serenity"]

[dependencies.dep_serenity]
package = "serenity"
version = "0.10"
default-features = false
features = ["model", "rustls_backend"]
optional = true
