[package]
name = "discord-message-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
once_cell = "1"
regex = "1"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["model", "rustls_backend"]
